---
- name: Wait for ssh connection
  hosts: all
  gather_facts: false
  tasks:
    - name: Enshure that instance are accessible
      ansible.builtin.wait_for:
        port: 22
        delay: 10
        timeout: 120
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars: 
        ansible_connection: local
- name: Install Docker & co
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.7
  tasks:
    - name: Enshure that requests, docker-compose & docker module are installed via pip3 to use community.docker
      pip:
        name:
          - requests
          - docker
          - docker-compose
        executable: pip3
    - name: Enshure Docker is installed
      ansible.builtin.yum:
        name: docker
        state: latest
        update_cache: yes
      register: docker_info
    - ansible.builtin.debug: msg={{docker_info}}
    - name: Enshure Docker Compose is installed
      ansible.builtin.get_url:
        # jinja template
        url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x

- name: Run docker container
  hosts: all
  become: true
  gather_facts: yes
  # vars_prompt:
  #   - name: docker_password
  #     prompt: Enter docker password
  vars:
    ansible_python_interpreter: /usr/bin/python3.7
  tasks:
    - name: Enshure Docker is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
    - name: Create a volume for portainer
      community.docker.docker_volume:
        name: portainer_data
    - name: Pull redis
      community.docker.docker_image:
        name: redis
        source: pull
    - name: Pull Portainer
      community.docker.docker_image:
        name: portainer/portainer
        source: pull
      register: docker_redis_info
    - ansible.builtin.debug: msg={{docker_redis_info}}
    - name: Copy docker-compose file to ec2
      ansible.builtin.copy:
        src: ~/Test-App/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Login to Docker(hub)
      community.docker.docker_login:
        username: wildarcticfox
        password: "<<REPLACE>>"
        reauthorize: yes
    - name: Run server from Docker compose
      community.docker.docker_compose:
        project_src: /home/ec2-user
        state: present
    - name: Restart a container portaoner
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer
        state: started
        restart: true
        ports:
          - "8000:8000"
          - "9443:9443"
        volumes:
          - portainer_data:/data
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
