---
- name: Install nodejs & npm
  hosts: droplet
  vars:
    - nodejs_version: 18
    - pm2_version: 5.2.0
  tasks:
    - name: Update apt repo & update_cache
      apt: update_cache=yes force_apt_get=yes
    # The NodeSource nodejs package contains both the node binary and npm
    - name: Download Node.js setup script
      command: curl -sL https://deb.nodesource.com/setup_{{nodejs_version}}.x -o /tmp/nodesource_setup.sh
    - name: Execute Bash script
      script: /tmp/nodesource_setup.sh
    - name: Install the nodejs
      apt:
        name: nodejs
        state: present
    - name: Install pm2 package
      community.general.npm:
        name: pm2
        global: yes
        version: "{{pm2_version}}"

- name: Create user
  hosts: droplet
  tasks:
    - name: Add the user 'admin' with a primary group of 'admin'
      ansible.builtin.user:
        name: admin
        comment: Alyona Admin
        group: admin

- name: Deploy nodejs app
  hosts: droplet
  become: True
  become_user: admin
  tasks:
    - name: Copy tar file to server
      ansible.builtin.copy:
        src: ~/mynodeapp-cicd-project/app/bootcamp-node-project-1.0.tgz
        dest: /home/admin/node-project-1.0.tgz
    - name: Unpack tar file on server
      ansible.builtin.unarchive:
        src: /home/admin/node-project-1.0.tgz
        dest: /home/admin/
        remote_src: yes
    - name: Install npm dependencies
      community.general.npm:
        path: /home/admin/package
    - name: Run server
      command: pm2 start /home/admin/package/server.js --force
    - name: Enshure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status}}
